name: Metrics
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create dist directory
        run: mkdir -p dist
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: dist/metrics.svg
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, yacc, vim script, shell, r, cmake, gnuplot
          plugin_languages_threshold: 0%
          plugin_habits: no
          plugin_habits_from: 50
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_trim: yes
          plugin_habits_languages_threshold: 0%
          plugin_lines: no
          plugin_traffic: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_API_KEY }}
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_followup: yes
          plugin_followup_sections: repositories
          config_order: isocalendar, languages, habits, traffic, pagespeed, stars, followup
          config_timezone: Europe/Madrid

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ github.token }}